[package]
name = "mini-kvstore-v2"
version = "0.2.0"
edition = "2021"
authors = ["whispem"]
description = "mini-kvstore-v2 â€” segmented append-only KV store (learning project)"
license = "MIT"

[lib]
name = "mini_kvstore_v2"
path = "src/lib.rs"

[[bin]]
name = "mini-kvstore-v2"
path = "src/main.rs"

[[bench]]
name = "kvstore_bench"
harness = false

[dependencies]
crc32fast = "1.3"
thiserror = "1.0"

[dev-dependencies]
criterion = "0.5"
anyhow = "1.0"
